language: node_js
node_js:
  - '10'

sudo: required
addons:
  chrome: stable

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

script:
  - npm run test-travis
  - npm run build
