language: node_js
node_js:
  - '10'

sudo: required
services:
  - xvfb
addons:
  chrome: stable

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm install

script:
  - npm run test-travis
  - npm run build
